finance/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^project/(?P<project_id>\d+)/advance/$', 'finance.views.project_advance', name='project_advance'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/$', 'finance.views.project_reimb', name='project_reimbursement'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d*)/$', 'finance.views.project_reimb', name='project_reimbursement_2'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d+)/save/$', 'finance.views.project_reimb_save', name='project_reimbursement_save'),
	url(r'^project/(?P<project_id>\d+)/bill/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.project_bills', name='project_bill'),
	url(r'^project/(?P<project_id>\d+)/$', 'finance.views.project_info', name='project_info'),

	url(r'^core/advance/$', 'finance.views.core_advance', name='core_advance'),
	url(r'^core/reimbursement/$', 'finance.views.core_reimb', name='core_reimbursement'),
	url(r'^core/$', 'finance.views.core_home', name='core_home'),

	url(r'^delete/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.delete_bill', name='delete_bill')

)

p_manage/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.core.urlresolvers import reverse
from userprofile.views import core_dashboard
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'p_manage.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url( r'^admin/', include(admin.site.urls)),
    url( r'^account/', include('userprofile.urls')),
    url( r'^finance/', include('finance.urls', namespace='finance')),
    url( r'^$', RedirectView.as_view( url = settings.SITE_URL+'account/user/' )), # testing base template. to be replaced with index.html soon.
    url( r'^', include('project.urls', namespace = 'project' ) ),
    url( r'^dashboard/core/$',core_dashboard, name='dashboard_core'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)
urlpatterns += patterns('django.views.static', (r'^static/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.STATIC_ROOT,
                        'show_indexes': True}))

urlpatterns += patterns('django.views.static', (r'^media/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.MEDIA_ROOT,
                        'show_indexes': True}))

finance/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from finance.models import *
from django.forms.models import modelformset_factory

CHOICES = (('approved', 'approved'), ('disapproved', 'disapproved'),)

class NewAdvanceForm(forms.ModelForm):

	class Meta:
		model = Advance
		fields = ('project', 'amount', 'split_up',)
		widgets = {'project': forms.HiddenInput}

class MentorApprovalForm(forms.ModelForm):

	class Meta:
		model = Advance
		fields = ('is_app_mentor', 'comments', 'project', 'amount', 'split_up',)
		readonly_fields = ('split_up', 'project', 'amount',)
		widgets = {	
			'comments': forms.Textarea(attrs={'cols': 70, 'rows': 3}),
			'project': forms.HiddenInput,
			'split_up': forms.HiddenInput,
			'amount': forms.HiddenInput,
			}

'''	def __init__(self, *args, **kwargs):  
		super(MentorApprovalForm, self).__init__(*args, **kwargs)
		self.fields["is_app_mentor"].choices = CHOICES	'''

MentorApprovalFormset = modelformset_factory(Advance, form=MentorApprovalForm)

class MentorApprovalForm2(forms.ModelForm):

	class Meta:
		model = Reimbursement
		fields = ('project', 'is_app_mentor', 'comments',)
		readonly_fields = ('project', )
		widgets = {
			'project': forms.HiddenInput,
			'comments': forms.Textarea(attrs={'cols': 40, 'rows': 3}),
			'is_app_mentor': forms.Select(attrs={'class':'status_field'}),
		}

'''	def __init__(self, *args, **kwargs):  
		super(MentorApprovalForm2, self).__init__(*args, **kwargs)
		self.fields["is_app_mentor"].choices = CHOICES	'''

MentorApprovalFormset2 = modelformset_factory(Reimbursement, form=MentorApprovalForm2)

class BillForm(forms.ModelForm):

	class Meta:
		model = Bill
		widgets = {'date': SelectDateWidget}

class InstallmentForm(forms.ModelForm):

	class Meta:
		model = Installment
		widgets = {'date': SelectDateWidget}

class CoreApprovalForm(forms.ModelForm):
	
	class Meta:
		model = Advance
		fields = ('project', 'amount', 'split_up', 'is_app_mentor', 'is_app_core', 'comments',)
		readonly_fields = ('project', 'is_app_mentor', 'is_app_core', 'split_up', 'amount',)
		widgets = {
			'project': forms.HiddenInput,
			'amount': forms.HiddenInput,
			'split_up': forms.HiddenInput,
			'is_app_mentor': forms.HiddenInput,
			'is_app_core': forms.Select(attrs={'class':'status_field'}),
			'comments': forms.Textarea(attrs={'rows':3, 'cols': 40}),
		}

'''	def __init__(self, *args, **kwargs):  
		super(CoreApprovalForm, self).__init__(*args, **kwargs)
		self.fields["is_app_core"].choices = CHOICES  '''

CoreApprovalFormset = modelformset_factory(Advance, form=CoreApprovalForm)	

class CoreApprovedForm(forms.ModelForm):
	
	class Meta:
		model = Advance
		fields = ('project', 'amount', 'split_up', 'is_app_mentor', 'is_app_core', 'approved_date', 'comments', 'installments')
		widgets = {
			'project': forms.HiddenInput,
			'amount': forms.HiddenInput,
			'approved_date': forms.HiddenInput,
			'split_up': forms.HiddenInput,
			'is_app_mentor': forms.HiddenInput,
			'is_app_core': forms.HiddenInput,
			'comments': forms.Textarea(attrs={'rows':3, 'cols': 40}),
		}

CoreApprovedFormset = modelformset_factory(Advance, form=CoreApprovedForm)

class CoreApprovalForm2(forms.ModelForm):
	
	class Meta:
		model = Reimbursement
		fields = ('project', 'is_app_mentor', 'is_app_core', 'comments',)
		readonly_fields = ('project', 'is_app_mentor', 'is_app_core',)
		widgets = {
			'project': forms.HiddenInput,
			'is_app_mentor': forms.HiddenInput,
			'is_app_core': forms.Select(attrs={'class':'status_field'}),
			'comments': forms.Textarea(attrs={'rows':3, 'cols': 40}),
		}

CoreApprovalFormset2 = modelformset_factory(Reimbursement, form=CoreApprovalForm2)	

class CoreApprovedForm2(forms.ModelForm):
	
	class Meta:
		model = Reimbursement
		fields = ('project', 'is_app_mentor', 'is_app_core', 'approved_date', 'comments', 'installments')
		widgets = {
			'project': forms.HiddenInput,
			'approved_date': forms.HiddenInput,
			'is_app_mentor': forms.HiddenInput,
			'is_app_core': forms.HiddenInput,
			'comments': forms.Textarea(attrs={'rows':3, 'cols': 40}),
		}

CoreApprovedFormset2 = modelformset_factory(Reimbursement, form=CoreApprovedForm2)

finance/views.py
from django.shortcuts import render
from finance.models import *
from finance.forms import *
from project.models import Project
from userprofile.models import UserProfile
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.forms import HiddenInput
from datetime import date
from django.contrib.auth.decorators import login_required

@login_required
def core_home(request):
	user = UserProfile.objects.get(user=request.user)
	if not user.is_finance_core:
		raise Http404
	b_infos = BudgetInfo.objects.all()
	years = Project.objects.all().values('year').distinct()
	a = []
	for y in years:
		a.append(y['year'])
	a.sort(reverse=True)
	cd = {'user': request.user, 'projects': b_infos, 'years': a, 'least': a[0],}
	return render(request, 'finance/core_home.html', cd)

@login_required
def core_advance(request):
	user = UserProfile.objects.get(user=request.user)
	if not user.is_finance_core:
		raise Http404

	post = False
	form_fail_p = False
	form_fail_a = False
	form_fail_i = False
	if request.method == 'POST':
		post = True
		if request.POST['form_type'] == 'pending':
			formset = CoreApprovalFormset(request.POST)
			if formset.is_valid():
				new = formset.save()
				for n in new:
					if n.is_app_core == 'approved':
						n.approved_date = date.today()
						n.save()
			else:
				form_fail_p = True
				pending_forms = formset
		elif request.POST['form_type'] == 'new_ins':
			new = InstallmentForm(request.POST)
			if new.is_valid():
				adv = Advance.objects.get(id=request.POST['adv_id'])
				n = new.save()
				adv.installments.add(n)
			else:
				form_fail_i = True
				install_form = new
		else:
			formset = CoreApprovedFormset(request.POST)
			if formset.is_valid():
				formset.save()
			else:
				form_fail_a = True
				approved_forms = formset

	pending = Advance.objects.filter(is_app_core='pending').filter(is_app_mentor='approved').order_by('-applied_date')
	approved = Advance.objects.filter(is_app_core='approved').order_by('applied_date')
	if not form_fail_p:
		pending_forms = CoreApprovalFormset(queryset=pending)
	if not form_fail_a:
		approved_forms = CoreApprovedFormset(queryset=approved)
	if not form_fail_i:
		install_form = InstallmentForm()
	pen = []
	app = []
	for p in range(len(pending)):
		pen.append([pending[p], pending_forms[p]])
	for p in range(len(approved)):
		app.append([approved[p], approved_forms[p]])	
	cd = {'user': request.user, 'pending': pen, 'approved': app, 'p_extra': pending_forms[-1], 'a_extra': approved_forms[-1]}
	cd['p_data'] = pending_forms.management_form
	cd['a_data'] = approved_forms.management_form
	cd['new_ins_form'] = install_form
	cd.update({'form_fail_i': form_fail_i, 'form_fail_p': form_fail_p, 'form_fail_a': form_fail_a, 'post': post})
	return render(request, 'finance/core_advance.html', cd)

@login_required
def core_reimb(request):
	user = UserProfile.objects.get(user=request.user)
	if not user.is_finance_core:
		raise Http404

	post = False
	form_fail_p = False
	form_fail_a = False
	form_fail_i = False
	if request.method == 'POST':
		post = True
		if request.POST['form_type'] == 'pending':
			formset = CoreApprovalFormset2(request.POST)
			if formset.is_valid():
				new = formset.save()
				print new
				for n in new:
					if n.is_app_core == 'approved':
						n.approved_date = date.today()
						n.save()
			else:
				form_fail_p = True
				pending_forms = formset
		elif request.POST['form_type'] == 'new_ins':
			new = InstallmentForm(request.POST)
			if new.is_valid():
				adv = Reimbursement.objects.get(id=request.POST['adv_id'])
				n = new.save()
				adv.installments.add(n)
			else:
				form_fail_i = True
				install_form = new
		else:
			formset = CoreApprovedFormset2(request.POST)
			if formset.is_valid():
				formset.save()
			else:
				form_fail_a = True
				approved_forms = formset

	pending = Reimbursement.objects.filter(is_app_core='pending').filter(is_app_mentor='approved').order_by('-applied_date')
	approved = Reimbursement.objects.filter(is_app_core='approved').order_by('applied_date')
	if not form_fail_p:
		pending_forms = CoreApprovalFormset2(queryset=pending)
	if not form_fail_a:
		approved_forms = CoreApprovedFormset2(queryset=approved)
	if not form_fail_i:
		install_form = InstallmentForm()
	pen = []
	app = []
	for p in range(len(pending)):
		pen.append([pending[p], pending_forms[p]])
	for p in range(len(approved)):
		app.append([approved[p], approved_forms[p]])	
	cd = {'user': request.user, 'pending': pen, 'approved': app, 'p_extra': pending_forms[-1], 'a_extra': approved_forms[-1]}
	cd['p_data'] = pending_forms.management_form
	cd['a_data'] = approved_forms.management_form
	cd['new_ins_form'] = install_form
	cd.update({'form_fail_i': form_fail_i, 'form_fail_p': form_fail_p, 'form_fail_a': form_fail_a, 'post': post})
	return render(request, 'finance/core_reimbursement.html', cd)

@login_required
def project_info(request, project_id):
	user = UserProfile.objects.get(user=request.user)
	project = Project.objects.get(id=project_id)
	if not user.is_in(project) and not user.is_finance_core:
		raise Http404	
	advances = Advance.objects.filter(project=project)
	reimbs = Reimbursement.objects.filter(project=project)
	info = BudgetInfo.objects.get(project=project)
	cd = {'advances': advances, 'reimbs': reimbs, 'info':info, 'project': project, 'user': request.user,}
	return render(request, 'finance/project_info.html', cd)

@login_required
def project_advance(request, project_id):
	user = UserProfile.objects.get(user=request.user)
	project = Project.objects.get(id=project_id)
	if not user.is_in(project):
		raise Http404	
	post = False
	advances = Advance.objects.filter(project=project).order_by('applied_date')
	new_adv_form = NewAdvanceForm(initial={'project':project,})
	cd = {'user': request.user, 'project': project, 'new_form': new_adv_form, 'advances': advances}

	if request.method == 'POST':
		post = True
		if request.POST['form_type'] == 'new_advance':
			new_adv = NewAdvanceForm(request.POST)
			if new_adv.is_valid():
				new_adv.save()
			else:
				cd['new_form'] = new_adv
		else:
			formset = MentorApprovalFormset(request.POST, prefix='mentor_formset')
			if formset.is_valid():
				formset.save()

	if user.is_mentor(project):
		mentor_forms = []
		queryset=Advance.objects.filter(is_app_mentor='pending').order_by('applied_date')
		formset = MentorApprovalFormset(queryset=queryset, prefix='mentor_formset')
		for i in range(len(queryset)):
			mentor_forms.append([queryset[i], formset[i]])
		extra_form = formset[-1]
		cd.update({'extra_form': extra_form, 'is_mentor': True, 'new_req_forms': mentor_forms, 'post': post})
		cd['formset_data'] = formset.management_form

	return render(request, 'finance/project_advance.html', cd)

@login_required
def project_reimb(request, project_id, col_id=None):
	user = UserProfile.objects.get(user=request.user)
	project = Project.objects.get(id=project_id)
	cd={}
	if not user.is_in(project):
		raise Http404
	if not col_id:
		initial = True
	else:
		initial = False
	post = False
	reimbs = Reimbursement.objects.filter(project=project).order_by('applied_date')
	bill_form = BillForm()
	bill_fail = False
	no_bills = True
	if request.method == 'POST':
		post = True
		if request.POST['form_type'] == 'add_bill':
			b = BillForm(request.POST, request.FILES)
			if b.is_valid():
				bi = b.save()
				bill_form = BillForm()
				if initial:
					col = Collection()
					col.save()
					col_id = col.id
				else:
					col = Collection.objects.get(id=col_id)
				col.bills.add(bi)
			else:
				bill_form = b
				bill_fail = True
		else:
			formset = MentorApprovalFormset2(request.POST, prefix='mentor_formset')
			if formset.is_valid():
				new = formset.save()

	if user.is_mentor(project):
		mentor_forms = []
		queryset=Reimbursement.objects.filter(is_app_mentor='pending').order_by('applied_date')
		formset = MentorApprovalFormset2(queryset=queryset, prefix='mentor_formset')
		for i in range(len(queryset)):
			mentor_forms.append([queryset[i], formset[i]])
		extra_form = formset[-1]
		cd.update({'extra_form': extra_form, 'is_mentor': True, 'new_req_forms': mentor_forms})
		cd['formset_data'] = formset.management_form

	if col_id:
		col = Collection.objects.get(id=col_id)
		cd['col'] = col
		no_bills = col.bills.all().count() == 0
	cd.update({'user': request.user, 'project': project, 'reimbs': reimbs, 'bill_fail': bill_fail, 'no_bills': no_bills, 'bill_form': bill_form,})
	cd['post'] = post
	if initial and col_id:
		return HttpResponseRedirect(reverse('finance:project_reimbursement_2', args=[project.id, col_id]))
	return render(request, 'finance/project_reimbursement.html', cd)

@login_required
def project_reimb_save(request, project_id, col_id):
	user = UserProfile.objects.get(user=request.user)
	project = Project.objects.get(id=project_id)
	if not user.is_in(project):
		raise Http404
	col = Collection.objects.get(id=col_id)
	r = Reimbursement(project=project)
	r.save()
	for c in col.bills.all():
		r.bills.add(c)
	col.delete()
	return HttpResponseRedirect(reverse('finance:project_reimbursement', args=[project.id]))

@login_required
def project_bills(request, project_id, objects, object_id):
	user = UserProfile.objects.get(user=request.user)
	project = Project.objects.get(id=project_id)
	if user.is_in(project):
		is_in = True
	elif user.is_finance_core:
		is_in = False
	else:
		raise Http404
	if objects == 'advance':
		ob = Advance.objects.get(id=object_id)
		if ob.is_app_core != 'approved':
			raise Http404
	elif objects == 'reimbursement':
		ob = Reimbursement.objects.get(id=object_id)
	else:
		raise Http404
	post = False
	bill_form = BillForm()
	bill_fail = False
	no_bills = ob.bills.all().count()==0

	if request.method == 'POST':
		post = True
		b = BillForm(request.POST, request.FILES)
		if b.is_valid():
			bi = b.save()
			bill_form = BillForm()
			ob.bills.add(bi)
		else:
			bill_form = b
			bill_fail = True

templates/finance/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<script type="text/javascript" src={% static 'finance.js' %}></script>
<link rel="stylesheet" type="text/css" href="{% static 'finance.css' %}">
{% endblock %}


{% block left_pane %}
<ul>
	<li class="heading"><span>Finance</span></li>
	<li class="hasSubmenu glyphicons stats">
		<a href="{% url 'finance:project_info' project.id %}">Info</a>
	</li>
	<li class="hasSubmenu glyphicons briefcase">
		<a href="{% url 'finance:project_advance' project.id %}">Advances</a>
	</li>
	<li class="hasSubmenu glyphicons usd">
		<a href="{% url 'finance:project_reimbursement' project.id %}">Reimbursements</a>
	</li>
</ul>
{% endblock %}

templates/finance/bills.html
{%extends 'finance/base.html'%}
{% load staticfiles %}


{% block scripts %}

{%  if bill_fail %}
	$(document).ready(function() {
		show_split('#add_bill_form');
	});
{% endif %}
{%  if post %}
	location.reload();
{% endif %}

{% endblock %}


{%block html_title%}
{{project.name}} - {{objects.capitalize}} - {{ob.applied_date}}
{%endblock%}


{% block content %}

<div id="dimmer" onclick="hide_split()"></div>
{% for bill in ob.bills.all %}
	<div id="soft_bill_{{bill.id}}" class="split_up_div">
		<img src="{{bill.image.url}}" style="height:400px;"></img>
	</div>
{% endfor %}
	
{% if objects == "advance" %}
	<div id="object_split" class="split_up_div">
		{{ob.split_up|safe}}
	</div>
	<div id="add_bill_form" class="split_up_div">
		<form name="new_bill_form" enctype="multipart/form-data" class="form-horizontal" id='new_bill_form' action="" method=post>
		{%csrf_token%}
			<div id="request_div">
			{{bill_form.as_p}}
			</div>
			<input type="submit" value="Save" class="btn btn-primary">
		</form>
	</div>

	<div id="object" class="content_divs first_con_div">
		<table class="table table-striped table-bordered table-condensed" id="object_table">
			<tr>
				<th>Applied Date</th>
				<th>Amount</th>
				<th>Approved Date</th>
				<th>Received</th>
				<th>Comments</th>
			</tr>
			<tr>
				<td>{{ob.applied_date}}</td>
				<td><a href="#object" onclick="show_split('#object_split')">{{ob.amount}}</a></td>
				<td>{{ob.approved_date}}</td>
				<td>{{ob.received}}</td>
				<td>{{ob.comments}}</td>
			</tr>
		</table>	
	</div>
{% endif %}

{% if objects == "reimbursement" %}
	<div id="object" class="content_divs first_con_div">
		<table class="table table-striped table-bordered table-condensed" id="object_table">
			<tr>
				<th>Applied Date</th>
				<th>Amount</th>
				<th>Status</th>
				<th>Approved Date</th>
				<th>Received</th>
				<th>Comments</th>
			</tr>
			<tr>
				<td>{{ob.applied_date}}</td>
				<td>{{ob.amount}}</td>
				<td>
					{% if ob.is_app_core == "disapproved" or ob.is_app_mentor == "disapproved" %}
						<span class="label label-danger">Disapproved</span>
					{% elif ob.is_app_core == "approved" %}
						<span class="label label-success">Approved</span>
					{% else %}
						<span class="label label-info">Pending</span>
					{% endif %}
				</td>
				<td>{{ob.approved_date}}</td>
				<td>{{ob.received}}</td>
				<td>{{ob.comments}}</td>				
			</tr>
		</table>	
	</div>
{% endif %}

{% if no_bills %}
<h4 id="no_bill_notif" style="text-align:center;margin-top:20px;">No bills added yet</h4>
{% else %}
<div id="bills_div" class="content_divs first_con_div">
	<table class="table table-striped table-bordered table-condensed" id="bills_table">
		<tr>
			<th>Shop</th>
			<th>Bill Number</th>
			<th>Amount</th>
			<th>Date</th>
			<th>Soft Copy</th>
			{% if objects == "advance" %}
			<th>Delete</th>
			{% endif %}
		<tr>
		{% for bill in ob.bills.all %}
		<tr id="bill_{{bill.id}}">
			<td>{{bill.shop}}</td>
			<td>{{bill.number}}</td>
			<td>{{bill.amount}}</td>
			<td>{{bill.date}}</td>
			<td><a onclick="show_split('#soft_bill_{{bill.id}}')"><span class="btn btn-xs btn-info">View</span></a></td>
			{% if objects == "advance" %}
			<td><a onclick="delete_bill('{% url 'finance:delete_bill' 'bill' bill.id %}')"><span class="glyphicon glyphicon-remove"></span></a></td>
			{% endif %}
		</tr>
		{% endfor %}
	</table>
	{% endif %}
	{% if objects == "advance" and is_in %}
	<h5 style="margin:0px;margin-bottom:10px;text-align:center"><a href="#add_bill" onclick="show_split('#add_bill_form')">+Add Bills</a></h5>
	{% endif %}
</div>


{% endblock %}

templates/finance/core_base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<script type="text/javascript" src={% static 'finance.js' %}></script>
<link rel="stylesheet" type="text/css" href="{% static 'finance.css' %}">
{% endblock %}


{% block left_pane %}
<ul>
	<li class="heading"><span>Finance</span></li>
	<li class="hasSubmenu glyphicons stats">
		<a href="{% url 'finance:core_home' %}">Info</a>
	</li>
	<li class="hasSubmenu glyphicons briefcase">
		<a href="{% url 'finance:core_advance' %}">Advances</a>
	</li>
	<li class="hasSubmenu glyphicons usd">
		<a href="{% url 'finance:core_reimbursement' %}">Reimbursements</a>
	</li>
</ul>
{% endblock %}

templates/finance/core_home.html
{% extends 'finance/core_base.html' %}


{%block html_title%}
Finance - Home
<div class="btn-group" style="margin-left:500px">
	{% for y in years %}
	<button type="button" class="btn btn-default" onclick="content_splitter('#{{y}}')">{{y}}</button>
	{% endfor %}
</div>
{% endblock %}


{% block content %}
{% for y in years %}
<div id="{{y}}" class="content_divs {% if y == least %}first_con_div{% endif %}">
	<h4 style="text-align:center;color:#37a6cd;margin:10px">{{y}}</h4>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th>Project</th>
			<th>Total Budget</th>
			<th>Utilized Budget</th>
			<th>Remaining Budget</th>
			<th>Dues</th>
		</tr>
		{% for p in projects %}
		{% if p.project.year == y %}
		<tr>
			<td>{{p.project.name}}</td>
			<td>{{p.total_budget}}</td>
			<td>{{p.util_budget}}</td>
			<td>{{p.rem_budget}}</td>
			<td>{{p.due}}</td>
		</tr>
		{% endif %}
		{% endfor %}
	</table>
</div>
{% endfor %}

{% endblock %}