finance/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^project/(?P<project_id>\d+)/advance/$', 'finance.views.project_advance', name='project_advance'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/$', 'finance.views.project_reimb', name='project_reimbursement'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d*)/$', 'finance.views.project_reimb', name='project_reimbursement_2'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d+)/save/$', 'finance.views.project_reimb_save', name='project_reimbursement_save'),
	url(r'^project/(?P<project_id>\d+)/bill/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.project_bills', name='project_bill'),
	url(r'^project/(?P<project_id>\d+)/$', 'finance.views.project_info', name='project_info'),

	url(r'^core/advance/$', 'finance.views.core_advance', name='core_advance'),
	url(r'^core/reimbursement/$', 'finance.views.core_reimb', name='core_reimbursement'),
	url(r'^core/$', 'finance.views.core_home', name='core_home'),

	url(r'^delete/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.delete_bill', name='delete_bill')

)

p_manage/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.core.urlresolvers import reverse
from userprofile.views import core_dashboard
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'p_manage.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url( r'^admin/', include(admin.site.urls)),
    url( r'^account/', include('userprofile.urls')),
    url( r'^finance/', include('finance.urls', namespace='finance')),
    url( r'^$', RedirectView.as_view( url = settings.SITE_URL+'account/user/' )), # testing base template. to be replaced with index.html soon.
    url( r'^', include('project.urls', namespace = 'project' ) ),
    url( r'^dashboard/core/$',core_dashboard, name='dashboard_core'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)
urlpatterns += patterns('django.views.static', (r'^static/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.STATIC_ROOT,
                        'show_indexes': True}))

urlpatterns += patterns('django.views.static', (r'^media/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.MEDIA_ROOT,
                        'show_indexes': True}))

project/urls.py
"""
 URL Patterns for the Project app.
"""



from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

#from accounts.views import AccountActivationView as ActivationView
from project.views import *

# the links given below link the three main project pages with their urls.
urlpatterns = patterns('',
                       url(r'project/(?P<project>\d+)/$',
                           project_detail_view,
                           name='project_detail'),

                       url(r'project/self/$',
                           MyProjectsListView.as_view(),
                           name='project_self'),

                       url(r'project/all/$',
                           AllProjectsListView.as_view(),
                           name='project_all'),

                       url(r'project/(?P<project>\d+)/upload/$',
                           upload_document,
                           name='project_upload'),

                       url(r'project/(?P<project>\d+)/update/add/$',
                           CreateUpdate.as_view(),
                           name='update_create'),

                       url(r'project/(?P<project>\d+)/task/add/$',
                           CreateTask.as_view(),
                           name='task_create'),

                       url(r'club/(?P<club>\d+)/$',
                           club_detail_view,
                           name='club_detail'),

                       url(r'project/(?P<project>\d+)/edit/$',
                           project_update,
                           name='project_update'),

                       url(r'club/(?P<club>\d+)/edit/$',
                           club_update,
                           name='club_update'),
                       
                       url(r'club/create/$',
                           TemplateView.as_view( template_name= 'project/club_create.html' ),
                           name='club_create'),
                       )

templates/base.html
{% load dajaxice_templatetags %}
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]>
<html xmlns="http://www.w3.org/1999/xhtml" class=""  lang="en-US">
<![endif]-->
{%load staticfiles%}
<!--[if !(IE 8) ]><!-->
{%load profile%}
<html xmlns="http://www.w3.org/1999/xhtml" class=""  lang="en-US">
<!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>{%block title%} {%endblock%} | {{user.first_name}} {{user.last_name}} | CFI Projects Management Portal</title>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/glyphicons.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/custom.css'%}">
        <script src="{%static 'javascript/jquery-1.11.0.min.js'%}"></script>
        <script src="{%static 'javascript/jquery.slimscroll.min.js'%}"></script>
        <script src="{%static 'javascript/jquery.cmtextconstrain.js'%}"></script>
        <script src="{%static 'javascript/custom.js'%}"></script>
		<!--<script src="static/javascript/bootstrap.js"></script> -->
        <script src="{%static 'javascript/bootstrap.min.js'%}"></script>
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<script type='text/javascript' src= {% static 'jquery.dajax.core.js' %} ></script>	
        {% dajaxice_js_import %}
        <style type="text/css">{% block style %}{% endblock %}</style>
		{% block head %}{% endblock %}
	
	</head>
	<body>
		<div id="container">
			<div id="header">
				<div class="navbar navbar-fixed-top">  
				  <div class="navbar-inner">  
						<div class="container"> 
							<ul class="nav">
							  <li class="active">
								<a class="brand oswald-bold" href="/">CFI Projects Management Portal</a>
							  </li>	
							  <li>
								<a href="#">About</a>
							  </li>
							  <li>
								<a href="#">Help</a>
							  </li>
							  <li>
								<a href="#">Contacts</a>
							  </li>
							</ul>
                            
							<ul class="nav pull-right">
							  <li class="dropdown" >  
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Profile <b class="caret" style="margin-top:0px;"></b></a>  
																<ul class="dropdown-menu" style="width:350px">  
									{% if not no_profile %}
                                    <img class="headerPPic" src="{%profile user as profiledata%}{{profiledata.pic.url}}">
                                    <li>
										<a href="#">{{user.first_name}} {{user.last_name}} aka. {{user.username}}</a>
									</li> 
									<li>
										<a href="#" style="padding-left: 30px; font-size: 12px;">{{user.email}}</a>
									</li> 
									{% endif %} 
									<li>
										<a href="{% url 'edit_account' %}">Settings</a>
									</li>
									<li>
										<a href="{% url 'edit_password' %}">Change Password</a>
									</li>  
									<li>
										<a href="{% url 'auth_logout' %}">Logout</a>
									</li>
                               </ul> 
															  </li>  
							</ul> 
						</div>
					</div>
				</div>
			</div>

<!--
				<div id="navbar">
					Navbar<br>
					Vineet Upadhyay <br>mail@example.com<a href='/updateForm.php'>Update Profile</a>					<br>Navbar ends<br><br>
				</div>
-->

<script type="text/javascript">
	{%block scripts%}{%endblock%}
</script><div id="menu" class="hidden-print hidden-sm">
			<div id="menuInner">

				<div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 1411px;"><div class="slim-scroll" data-scroll-height="420px" style="overflow: hidden; width: auto; height: 1411px;">
				
				<div id="search">
					<input type="text" placeholder="Quick search ...">
					<button class="glyphicons search"></button>
				</div>
				<ul>
					<li class="heading"><span>Category</span></li>
					<li class="glyphicons dashboard"><a href="{%url 'dashboard_core'%}"><span>Dashboard</span></a></li>
					<li class="hasSubmenu">
						<a data-toggle="collapse" class="glyphicons settings" href="#menu_account"><span>My Account</span></a>
						<ul class="menuCollapse" id="menu_account">
							<li class=""><a href="{% url 'edit_account' %}"><span>Edit account</span></a></li>
							<li class=""><a href="{% url 'edit_password' %}"><span>Change Password</span></a></li>
							<li class=""><a href="{% url 'auth_logout' %}"><span>Logout</span></a></li>
						</ul>
					</li>
					<li class="hasSubmenu">
						<a data-toggle="collapse" class="glyphicons link" href="#menu_components"><span>Links</span></a>
						<ul class="menuCollapse" id="menu_components">
							<li class=""><a href="http://www.cfi-iitm.org/"><span>CFI</span></a></li>
							<li class=""><a href="http://www.iitm.ac.in"><span>IIT Madras</span></a></li>
							<li class=""><a href="https://icandsr.iitm.ac.in/‎"><span>ICSR</span></a></li>
							<li class=""><a href="http://www.ccw.iitm.ac.in"><span>CCW</span></a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li class="heading"><span>Memberships</span></li>
					<li class="hasSubmenu">
						<a data-toggle="collapse" class="glyphicons pencil" href="#menu_projects"><span>Projects</span></a>
						<ul class="menuCollapse" id="menu_projects">
							<li class=""><a href="{% url 'project:project_all' %}"><span>All Projects</span></a></li>
							<li class=""><a href="{% url 'project:project_self'%}"><span>My Projects</span></a></li>
						</ul>
					</li>
					<!--<li class="glyphicons notes"><a href="javascript:update_content('Projects');"><span>Projects</span></a></li>-->
					<li class="hasSubmenu">
						<a data-toggle="collapse" class="glyphicons tower" href="#menu_clubs"><span>Clubs</span></a>
						<ul class="menuCollapse" id="menu_clubs">
							{%for club in club_list%}
							<li class=""><a href="{% url 'project:club_detail' club.pk%}"><span>{{club.name}}</span></a></li>
							{%endfor%}
							<li class=""><a href="{% url 'project:club_create'%}">Create a Club</a></li>
						</ul>
					</li>
					<li class="glyphicons group"><a href="#"><span>People</span></a></li>
				</ul>
				{% block left_pane %}{% endblock %}
				</div>
				</div>
			
			</div>
			<!-- // Nice Scroll Wrapper END -->
			
		</div>
<!--<div id='content' class='row-fluid' style="margin-top:50px;">
	<div class='span3 sidebar'> 
		<ul class="nav nav-list">  
			<li class="nav-header">List header</li>  
			<li class="active"><a href="#"><i class="icon-white icon-home"></i> Home</a></li>  
			<li><a href="#"><i class="icon-book"></i> Library</a></li>  
			<li><a href="#"><i class="icon-pencil"></i> Applications</a></li>  
			<li class="nav-header">Another list header</li>  
			<li><a href="#"><i class="icon-user"></i> Profile</a></li>  
			<li><a href="#"><i class="icon-cog"></i> Settings</a></li>  
			<li class="divider"></li>  
			<li><a href="#"><i class="icon-flag"></i> Help</a></li>  
		</ul>
		
	</div>
	<div class='span9 main'>
		<h2>Main Content Section</h2>
	</div>
</div>-->   
	<div id="content">
		<ul class="breadcrumb">
			<li><a href="index.php" class="glyphicons home">CFI PMP</a></li>
			<li class="divider"></li>
			{%block breadcrumb%}
			{%endblock%}
		</ul>
		<div class="separator bottom"></div>
		<div class="heading-buttons">
			<h3 class="glyphicons display">{%block html_title%}{%endblock%}</h3>
			<div class="clearfix" style="clear: both;"></div>
		</div>
		<div class="separator bottom"></div>

		<div class="separator bottom"></div>
		<div id="var_content">
			{%block content%}
			{%endblock%}
		</div>
	</div>
				</div>
			</div>
		</div>	
		<div id="returnMessage">
					</div>
	</div>

			<div id="footer" style="height:50px;" >
				<div style="font-size:14px; color:#fff; padding: 4px 10px; font-family:Oswald; font-weight:300; text-align:center;" >
					Project allocations have been declared, please login to check.<br>
					For any login problems please contact - 1) Vineet ( 9445505731 )  2) Dharani ( 9043814168 ) or write a mail to <a style="color:#fff;" href="mailto:cfi.iitmadras@gmail.com">cfi.iitmadras@gmail.com</a>
				</div>
			</div>
		</div> <!-- container -->
	</body>
</html>

<style>