finance/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^project/(?P<project_id>\d+)/advance/$', 'finance.views.project_advance', name='project_advance'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/$', 'finance.views.project_reimb', name='project_reimbursement'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d*)/$', 'finance.views.project_reimb', name='project_reimbursement_2'),
	url(r'^project/(?P<project_id>\d+)/reimbursement/(?P<col_id>\d+)/save/$', 'finance.views.project_reimb_save', name='project_reimbursement_save'),
	url(r'^project/(?P<project_id>\d+)/bill/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.project_bills', name='project_bill'),
	url(r'^project/(?P<project_id>\d+)/$', 'finance.views.project_info', name='project_info'),

	url(r'^core/advance/$', 'finance.views.core_advance', name='core_advance'),
	url(r'^core/reimbursement/$', 'finance.views.core_reimb', name='core_reimbursement'),
	url(r'^core/$', 'finance.views.core_home', name='core_home'),

	url(r'^delete/(?P<objects>[a-z]+)/(?P<object_id>\d+)/$', 'finance.views.delete_bill', name='delete_bill')

)

p_manage/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.core.urlresolvers import reverse
from userprofile.views import core_dashboard
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'p_manage.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url( r'^admin/', include(admin.site.urls)),
    url( r'^account/', include('userprofile.urls')),
    url( r'^finance/', include('finance.urls', namespace='finance')),
    url( r'^$', RedirectView.as_view( url = settings.SITE_URL+'account/user/' )), # testing base template. to be replaced with index.html soon.
    url( r'^', include('project.urls', namespace = 'project' ) ),
    url( r'^dashboard/core/$',core_dashboard, name='dashboard_core'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)
urlpatterns += patterns('django.views.static', (r'^static/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.STATIC_ROOT,
                        'show_indexes': True}))

urlpatterns += patterns('django.views.static', (r'^media/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.MEDIA_ROOT,
                        'show_indexes': True}))

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

HOSTELS = (('Alakananda', 'Alakananda'), ('Brahmaputra', 'Brahmaputra'), ('Cauvery', 'Cauvery'),
('Ganga', 'Ganga'), ('Godavari', 'Godavari'), ('Jamuna', 'Jamuna'), ('Krishna', 'Krishna'),
('Mahanadhi', 'Mahanadhi'), ('Mandakini', 'Mandakini'), ('Narmada', 'Narmada'), ('Pamba', 'Pamba'),
('Saraswathi', 'Saraswathi'), ('Sarayu','Sarayu'), ('Sharavati', 'Sharavati'),
('Sindhu', 'Sindhu'), ('Tamraparani', 'Tamraparani'), ('Tapti', 'Tapti'))

class UserProfile( models.Model ):

	user = models.ForeignKey( User )
	description = models.TextField( max_length = 2500, null=True, blank=True)
	roll_num = models.CharField(max_length=8)
	ph_num = models.CharField(max_length = 10)
	hostel = models.CharField( max_length = 30, choices=HOSTELS, blank=False)
	room = models.CharField( max_length = 4)
	expertise = models.CharField( max_length = 2500, null=True, blank=True)
	social_media_URL = models.CharField( max_length = 500, null=True, blank=True)
	pic = models.ImageField( upload_to = 'user_pics/', default = 'user_pics/default.jpg')
	is_finance_core = models.BooleanField(default=False)

	def __unicode__(self):
		return self.user.username

	def is_member(self, project):
		if self.user in project.users.all():
			return True
		else:
			return False

	def is_mentor(self, project):
		if self.user in project.mentors.all():
			return True
		else:
			return False

	def is_in(self, project):
		if self.is_mentor(project) or self.is_member(project):
			return True
		else:
			return False

userprofile/forms.py
from django import forms
from userprofile.models import UserProfile

class UserProfileForm(forms.ModelForm):

	first_name = forms.CharField(max_length = 30)
	last_name = forms.CharField(max_length = 30)

	class Meta:
		model = UserProfile
		exclude = ('user',)
		widgets = {
			'description': forms.Textarea(attrs={'cols': 100, 'rows': 5})
		}

	def __init__(self, *args, **kwargs):
		super(UserProfileForm, self).__init__(*args, **kwargs)
		self.fields.keyOrder = ['first_name', 'last_name', 'ph_num', 'roll_num', 'hostel', 'room', 'expertise', 
			'social_media_URL', 'description', 'pic']

class ChangePasswordForm(forms.Form):
	current_password = forms.CharField(widget=forms.PasswordInput())
	new_password = forms.CharField(widget=forms.PasswordInput())
	repeat_password = forms.CharField(widget=forms.PasswordInput())

templates/user/change_password.html
{%extends 'base.html'%}

{% block scripts %}

function check_password() {
	if($('#id_new_password').val() == $('#id_repeat_password').val()) return true;
	else {
		alert("Passwords don't match!");
		return false;
	}
}

{% if auth_fail %}
$(document).ready(function(){
	alert('Incorrect Password!');
});
{% endif %}

{% endblock %}

{%block html_title%}
	Change Password
{%endblock%}

{%block content %}
	<div id="UpdatePasswordDiv">  
		<form name="passwordForm" onsubmit="return check_password()" enctype="multipart/form-data" class="form-horizontal" id='profile-form' action="/account/password/" method=post>
		{%csrf_token%}	
			{{form.as_ul}}
			<input type="submit" value="Save Changes" class="btn btn-primary">
		</form>			
	</div>

{% endblock %}

templates/user/dashboard_core.html
{%extends 'base.html'%}

{%block html_title%}Core Dashboard{%endblock%}
{%block title%}Core Dashboard{%endblock%}

templates/user/edit_account.html
{%extends 'base.html'%}

{%block html_title%}
	Edit Account
{%endblock%}


{% block scripts %}

function check_ph() {
	if ($('#id_ph_num').val().length != 10) { alert('Input a 10-digit phone number'); return false; }
	else return true;
}

{% endblock %}


{%block content %}
	
	<div id="UpdateDiv">
		{% if no_profile %}
		<h5 style="color:red">*Other features of the portal will not work before you fill out your profile</h5>
		{% endif %}
		<form name="updateForm" enctype="multipart/form-data" class="form-horizontal" id='profile-form' action="/account/upload/" onsubmit="return check_ph()" method=post>
		{% csrf_token %}	
			{{form.as_ul}}
			<input type="submit" value="Save Changes" class="btn btn-primary">
		</form>
	</div>  

{%endblock%}

templates/user/edit_account1.html
{%extends 'base.html'%}

{%block html_title%}
	Edit Account
{%endblock%}

{%block content %}
	<div class="widget widget-2 widget-tabs widget-tabs-2">
		<div class="tab-content">
			<div class="tab-pane active" id="basic-profile-tab">
				<div id="UpdateDiv">
					<form name="updateForm" class="form-horizontal" action="index.php?action=update" method="POST">
						<table>
							<tbody><tr>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input01">Name</label>  
										<div class="controls">  
										  <input type="text" name="name" class="input-xlarge" value="Vineet Upadhyay " id="input01">  
										  <p class="help-block"></p>  
										</div>  
									</div> 
								</td>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input02">Room</label>  
										<div class="controls">  
										  <input type="text" name="room" class="input-xlarge" value="344" id="input02">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
							   </td>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input03">Hostel</label>  
										<div class="controls">  
										  <input type="text" name="hostel" class="input-xlarge" value="Tamiraparani" id="input03">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
							</tr>
							<tr>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input04">Phone</label>  
										<div class="controls">  
										  <input type="text" name="phone" class="input-xlarge" value="9445505731" id="input04">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input05">Expertise</label>  
										<div class="controls">  
										  <input type="text" name="expertise" class="input-xlarge" value="Arduino" id="input05">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input06">Social Media URL</label>  
										<div class="controls">  
										  <input type="text" name="socialMediaUrl" class="input-xlarge" value="" id="input06">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
							</tr>
							<tr>
								<td colspan="3">							   
									<div class="control-group">  
										<label class="control-label" for="input07">About Me</label>  
										<div class="controls">  
										  <textarea style="width:500px; font-family:Oswald;" type="text" name="aboutMe" class="input-xlarge" id="input07"></textarea>
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<div class="form-actions" style="border:none;">  
										<center>
											<input type="submit" name="updateFormSubmit" class="btn btn-primary" value="Save changes">
										</center>  
									</div>  
								</td>
							</tr>
						</tbody></table>
					</form>
				</div>   
	
			</div>
			<div class="tab-pane" id="password-tab">
				<div id="UpdatePasswordDiv">                            	
					<form name="updatePasswordForm" class="form-horizontal" action="index.php?action=updatePassword" method="POST">	     
						<table>
							<tbody><tr>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input08">New Password</label>  
										<div class="controls">  
										  <input type="password" name="password" placeholder="Choose Password" id="input08">  
										  <p class="help-block"></p>  
										</div>  
									</div> 	
								</td>
								<td>
									<div class="control-group">  
										<label class="control-label" for="input09">Confirm New Password</label>  
										<div class="controls">  
										  <input type="password" name="password_confirmation" placeholder="Re-type Password" id="input09">
										  <p class="help-block"></p>  
										</div>  
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<div class="form-actions">  
										<center>
											<input name="update_password_form" type="submit" class="btn btn-primary" value="Save changes">
										</center>  
									</div>  
								</td>
							</tr>
						</tbody></table>
					</form>
				</div>
			</div>
			
			<div class="tab-pane" id="profile-pic-tab">
				<div id="updateProfilePic">
				   <form name="updateprofilepic" class="form-horizontal" action="index.php?action=updateProfilePic" method="POST" enctype="multipart/form-data">
						<table>
							<tbody><tr>
								<td>
									<div class="control-group">
										<label class="control-label" for="profpic">ProfilePic</label>
										<div class="controls">
											<input type="file" name="file" id="profpic">
											<p class="help-block"></p>
										</div>
									</div>
								</td>
								<td>
									<img style="height:200px;" src="upload/ProfilePics/14.jpg"> 
								</td>
							</tr>
							<tr>
								<td colspan="2">									
									<div class="form-actions" style="border:none;">  
										<center>
											<input type="submit" class="btn btn-primary" value="Update">
										</center>  
									</div>  
								</td>
							</tr>
						</tbody></table>
					</form>
				<div>
			</div>
		</div>
	</div>	
    
	

	

	
	<div id="returnMessage">
			</div>
    <script>
		$('#myTab a').click(function (e) {
		  e.preventDefault()
		  $(this).tab('show')
		})
	</script>

</div></div>

{%endblock%}

templates/user/get_form.html
<form name="updateForm" enctype="multipart/form-data" class="form-horizontal" id='profile-form' action="/account/upload/" method=post>
{%csrf_token%}	
	{{form.as_ul}}
	<input type="submit" value="Save Changes" class="btn btn-primary">
</form>

templates/user/user_tile.html
{%load profile%}
<div class="col-md-12" style="height:100px">
	{%profile userdata as profildata%}
	<div class="col-md-2">
		<img src="{{profiledata.pic.url}}" height="100%">
	</div>
	<div class="col-md-10">
		<h5>{{userdata.first_name}} {{usedata.last_name}} aka. {{userdata.username}}</h5>
		<p>{{profiledata.room}},{{profiledata.hostel}}</p>
	</div>
</div>